
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 10;
  public static final int SUM = 2;
  public static final int CP = 7;
  public static final int RES = 3;
  public static final int FIN = 9;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int NEG = 8;
  public static final int MUL = 4;
  public static final int AP = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "AP",
  "CP",
  "NEG",
  "FIN",
  "NUM"
  };
}

